# Generated by Django 4.1.6 on 2023-02-18 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10, verbose_name='Статус')),
                ('text', models.TextField(max_length=3000, null=True, verbose_name='Текст')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Цена')),
                ('image_url', models.TextField(max_length=3000, null=True, verbose_name='Фото')),
                ('create_at', models.DateField(verbose_name='Дата добавления')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_category', models.CharField(max_length=10, verbose_name='Статус')),
                ('text_category', models.TextField(max_length=3000, null=True, verbose_name='Текст')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='categories', to='webapp.article', verbose_name='Продукты')),
            ],
        ),
    ]
