# Generated by Django 4.1.6 on 2023-02-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('other', 'разное'), ('technique', 'техника'), ('cloth', 'одежда'), ('toys', 'игрушки')], default='other', max_length=20, verbose_name='Категория')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('text', models.TextField(max_length=2000, null=True, verbose_name='Текст')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Цена')),
                ('remainder', models.IntegerField(verbose_name='Остаток')),
                ('image_url', models.TextField(max_length=3000, null=True, verbose_name='Фото')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
        ),
    ]
